#define c2wasm_false 0
#define c2wasm_true 1
#define c2wasm_null 2
#define c2wasm_undefined 3
#define c2wasm_arguments 4
#define c2wasm_window 5
#define c2wasm_document 6
#define c2wasm_body 7
#define c2wasm_error 8
typedef long c2wasm_js_var;