
#define C2WASM_UNDEFINED_TYPE 0
#define C2WASM_NULL_TYPE 1
#define C2WASM_BOOLEAN_TYPE 2
#define C2WASM_NUMBER_TYPE 3
#define C2WASM_STRING_TYPE 4
#define C2WASM_OBJECT_TYPE 5
#define C2WASM_ARRAY_TYPE 6
#define C2WASM_FUNCTION_TYPE 7
#define C2WASM_SYMBOL_TYPE 8
#define C2WASM_BIGINT_TYPE 9
